### ISSUE TITLE
set image in specific position

### ISSUE THREAD

**Issue by shawnyeh** [killua99/views_pdf#14]
Sorry for this stupid question, but I've tried many settings, still can't get image on location I want.

Like attached image, I want to make third image in location like other two, but after I set Y position to more than 160, image jump to a new page, the maximum of Y position setting is 162, but it still can't fit what I need. please help me find out how, Thank you so much.
![7-9-2015 12-16-22 pm](https://cloud.githubusercontent.com/assets/5384439/8601854/7a0b2cbc-2634-11e5-9f44-62c0c14a8125.png)

**Comment by vegansupreme** [comment]
Have you tried setting the bottom margin to a negative value?

**Comment by shawnyeh** [comment]
Thanks, brother, you solved the problem.
I changed the PDF page settings, the bottom margin to negative 10, solved this issue.
